### ISSUE TITLE
[Documentation] support issue template for docs request

### ISSUE THREAD

**Issue by yeonns** [euphony-io/euphony-hub-collector#13]
### What is the improvement or update you wish to see?
There's no "docs request" issue template, so it is hard to request documentation.

### Is there any context that might help us understand?
We need to compare other open source's issue template and apply ours.
If you feel hard to figure out how to resolve this issue, please refer #9 and check @designe 's comments.

### Does the docs page already exist? Please link to it.
No

**Comment by Chandra-Sekhar-Bala** [comment]
You can assign this to me :)
