### ISSUE TITLE
CI with github action

### ISSUE THREAD

**Issue by yeonns** [euphony-io/euphony-hub-collector#17]
## Description
If pull request is created to ```master``` branch, to check whether this PR has problem, it is nice to make CI process.
Generally, github action is ```.github/workflows/xxx.yml``` in repository.
Feel free to suggest filename for yml and what steps should be included in CI.

**Comment by Chandra-Sekhar-Bala** [comment]
Well, I haven't done it yet. But I'm eager to learn and contribute to this.
