### ISSUE TITLE
upgrade euphony library version

### ISSUE THREAD

**Issue by yeonns** [euphony-io/euphony-hub-collector#3]
## Description
Now euphony-collector supports euphony ```v0.7.1.6```, but ```v0.8``` is released, and changes are listed in this [link](https://github.com/euphony-io/euphony/discussions/42).
```v0.8``` supports a lot of features, so if we upgrade version, we can add more functionalities in euphony-collector.

**Comment by designe** [comment]
Due to domain issues, euphony library v0.8 is not published yet.
So, this issue should be pending by august 16th 😢
