### ISSUE TITLE
[Request] change the package name

### ISSUE THREAD

**Issue by designe** [euphony-io/euphony-hub-collector#37]
### Does the feature exist in the most recent commit?

- [ ] It doesn't exist.

### Describe the proposal

This repository's package is ```co.jbear.euphony_hub_collector``` 

but we need to change it to ```co.euphony.euphony_hub_collector```
because we need to unify the package name with `euphony` project 
https://github.com/euphony-io/euphony/tree/master/euphony/src/main/java/co/euphony

### Why do we need this feature?

package name from `co.jbear.euphony_hub_collector` to `co.euphony.euphony_hub_collector`

### Describe alternatives you've considered

-

**Comment by nodobi** [comment]
I just make a PR about this issue. please check it! 😊

https://github.com/euphony-io/euphony-hub-collector/pull/38
